"""Initial migration with custom order fields

Revision ID: 98b6fe8c0ec7
Revises: 
Create Date: 2025-06-23 13:46:22.949821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b6fe8c0ec7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cake_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('frosting', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('topper', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('theme', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('reference_img', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('estimated_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('estimated_price')
        batch_op.drop_column('reference_img')
        batch_op.drop_column('theme')
        batch_op.drop_column('topper')
        batch_op.drop_column('frosting')
        batch_op.drop_column('cake_type')

    # ### end Alembic commands ###
